// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDErKNUgSh8efzr7nAsIRBLVK9XLFS0Vv8',
    appId: '1:878720279008:web:2f1ae3eaf02be3e35bcb85',
    messagingSenderId: '878720279008',
    projectId: 'flutter-test-4232d',
    authDomain: 'flutter-test-4232d.firebaseapp.com',
    storageBucket: 'flutter-test-4232d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU6k6OoPe224MZlTyu_ZYcoWBe3Pq0Exw',
    appId: '1:878720279008:android:d3324a789699b5045bcb85',
    messagingSenderId: '878720279008',
    projectId: 'flutter-test-4232d',
    storageBucket: 'flutter-test-4232d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqcx9cv42N9_hnBx4gt12dTdEI7IRRE-M',
    appId: '1:878720279008:ios:0c65e6bb25ec04fd5bcb85',
    messagingSenderId: '878720279008',
    projectId: 'flutter-test-4232d',
    storageBucket: 'flutter-test-4232d.appspot.com',
    iosBundleId: 'com.example.geminiChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqcx9cv42N9_hnBx4gt12dTdEI7IRRE-M',
    appId: '1:878720279008:ios:0c65e6bb25ec04fd5bcb85',
    messagingSenderId: '878720279008',
    projectId: 'flutter-test-4232d',
    storageBucket: 'flutter-test-4232d.appspot.com',
    iosBundleId: 'com.example.geminiChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDErKNUgSh8efzr7nAsIRBLVK9XLFS0Vv8',
    appId: '1:878720279008:web:bd346f88d1e04ccb5bcb85',
    messagingSenderId: '878720279008',
    projectId: 'flutter-test-4232d',
    authDomain: 'flutter-test-4232d.firebaseapp.com',
    storageBucket: 'flutter-test-4232d.appspot.com',
  );
}
